#!/usr/bin/python

import sys
import lib
import string
import argparse

overlay="Video Overlay 2"

if __name__ == "__main__":
	vb = lib.VidBlaster()
	parser = argparse.ArgumentParser(description="Send hymn text to vidblaster")
	parser.add_argument('--overlay','-o',help="Overlay to send text to",default='overlay')
	parser.add_argument('--file','-f',help="File containing text of hymn",required=True)
	args = parser.parse_args()

	text = open(args.file).readlines()

	if (len(text)%2!=0):
		text.append("");
	text = [i.rstrip().upper() for i in text]
	t = zip(text[0::2],text[1::2])
	chunks = ["\\n".join(i) for i in t]
	chunks = [string.replace(i,",","\\x2c") for i in chunks]

	vb.sendTextToOverlay("\\x20",overlay)
	vb.turnOverlay(True,overlay)

	try:
		for c in chunks:
			print "Press return to send Next Line: ",c
			inp = raw_input()
			vb.sendTextToOverlay(c,overlay)
		print "Press enter for clear song"
		inp = raw_input()
	except KeyboardInterrupt:
		pass

	vb.turnOverlay(False,overlay)
