#!/usr/bin/python

# vb_text blaster sends text to the overlay of a vidblaster computer.
# Copyright (C) 2013  Evan Felix and Nathan Tenney

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import sys
import lib
import string

overlay="Video Overlay 1"

if __name__ == "__main__":
	vb = lib.VidBlaster()
	img = lib.genTextPNG(' '.join(sys.argv[1:]))
	vb.sendPNGToOverlay(img.make_blob(format="png"),overlay)
