#!/usr/bin/python

# vb_text blaster sends text to the overlay of a vidblaster computer.
# Copyright (C) 2013  Evan Felix and Nathan Tenney

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import sys
import lib
import string
import argparse

overlay="Video Overlay 2"

if __name__ == "__main__":
	vb = lib.VidBlaster()
	parser = argparse.ArgumentParser(description="Send hymn text to vidblaster")
	parser.add_argument('--overlay','-o',help="Overlay to send text to",default='overlay')
	parser.add_argument('--file','-f',help="File containing text of hymn",required=True)
	args = parser.parse_args()

	text = open(args.file).readlines()

	if (len(text)%2!=0):
		text.append("");
	text = [i.rstrip().upper() for i in text]
	t = zip(text[0::2],text[1::2])
	chunks = ["\\n".join(i) for i in t]
	chunks = [string.replace(i,",","\\x2c") for i in chunks]

	vb.sendTextToOverlay("\\x20",overlay)
	vb.turnOverlay(True,overlay)

	try:
		for c in chunks:
			print "Press return to send Next Line: ",c
			inp = raw_input()
			vb.sendTextToOverlay(c,overlay)
		print "Press enter for clear song"
		inp = raw_input()
	except KeyboardInterrupt:
		pass

	vb.turnOverlay(False,overlay)
