#!/usr/bin/python

import sys
import lib
import string
import time

overlay="Video Overlay 1"

if __name__ == "__main__":
	vb = lib.VidBlaster()
	vb.sendTextToOverlay("\\x20",overlay)
	vb.turnOverlay(True,overlay)
	i = ' '.join(sys.argv[2:])
	i = string.replace(i,",","\\x2c")
	vb.sendTextToOverlay(i+"\\n",overlay)
	time.sleep(int(sys.argv[1]))

	vb.turnOverlay(False,overlay)
